# Creates myDitionary with David=4045551234, Lucy=4045555678
# Vrushali=4045559101
myDicionary ={
   "David": 4045551234,
   "Lucy": 4045555678,
   "Vrushali": 4045559101
}
print(myDicionary["Dana"])

# #Output is a KeyError:
# Traceback (most recent call last):
#   File "cs1301x-code-revision\module-3-data-structures\chapter-04\sect-4-5-dicts\example_4_5_05_add_remove_3.py", line 8, in <module>
#     print(myDicionary["Dana"])
#           ~~~~~~~~~~~^^^^^^^^
# KeyError: 'Dana'
